### ISSUE TITLE
申请添加新功能

### ISSUE THREAD

**Issue by stardock** [HenryQuan/WoWs-Info-Origin#29]
**我确认我做到了** (使用 "x" 选择)  

- [x] 将软件升级到最新版  

**我正在申请**  (使用 "x" 选择)  

- [x] 申请添加新的特性或功能或者好的想法  

wows里面可以设置一个专有链接用于查看自己profile的信息，wowsinfo能不能设置通过这个链接读取信息?  
(本菜鸡不想让别人看到自己的渣战绩)

**Comment by HenryQuan** [comment]
战绩是否公开是有由wargaming那边决定的。如果不想让别人看到自己的战绩的话，可以隐藏自己的数据。但是这样的话wows info也没有办法读取。
