### ISSUE TITLE
Suggest of Warship filtering

### ISSUE THREAD

**Issue by flying0420** [HenryQuan/WoWs-Info-Origin#9]
Hi,

Is it possible to add some filter in Warship page? It looks not cool as expected.

Suggesting fiter:

1. By numbers of combat
2. By winning rate
3. By all the other major meta data

It will be appreciated if it could be done. Thank you!

**Comment by HenryQuan** [comment]
Yes, I actually did it before but it was not ideal. I am currently redesigning the filter system.

**Comment by HenryQuan** [comment]
Hi there, it has been a while.
I will be working on warship filter really soon and it is now possible to advance warship filtering. An update will come soon.

**Comment by HenryQuan** [comment]
Hello again, this feature has been implemented now. Best testing is gonna come soon and the update will be available on the 1st April.
I will close this issue for now.
